CREATE TABLE [dbo].[SERVICIO]
(
[IDSER] [int] NOT NULL IDENTITY(1, 1),
[DESSER] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VALSER] [decimal] (6, 2) NOT NULL,
[TIPSER] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SERVICIO] ADD CONSTRAINT [SERVICIO_pk] PRIMARY KEY CLUSTERED  ([IDSER]) ON [PRIMARY]
GO
