CREATE TABLE [dbo].[COMPROMISO]
(
[IDCOM] [int] NOT NULL IDENTITY(1, 1),
[IDSER] [int] NOT NULL,
[IDPER] [int] NOT NULL,
[ESTCOMP] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FECHCOMP] [date] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COMPROMISO] ADD CONSTRAINT [COMPROMISO_pk] PRIMARY KEY CLUSTERED  ([IDCOM]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COMPROMISO] ADD CONSTRAINT [COMPROMISO_PERSONA] FOREIGN KEY ([IDPER]) REFERENCES [dbo].[PERSONA] ([IDPER])
GO
ALTER TABLE [dbo].[COMPROMISO] ADD CONSTRAINT [COMPROMISO_SERVICIO] FOREIGN KEY ([IDSER]) REFERENCES [dbo].[SERVICIO] ([IDSER])
GO
