CREATE TABLE [dbo].[DETALLE_INGRESO]
(
[IDDET] [int] NOT NULL IDENTITY(1, 1),
[IDING] [int] NOT NULL,
[IDSER] [int] NOT NULL,
[MONTDET] [decimal] (6, 2) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DETALLE_INGRESO] ADD CONSTRAINT [DETALLE_INGRESO_pk] PRIMARY KEY CLUSTERED  ([IDDET]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DETALLE_INGRESO] ADD CONSTRAINT [DETALLE_APAFA_APAFA] FOREIGN KEY ([IDING]) REFERENCES [dbo].[INGRESO] ([IDING])
GO
ALTER TABLE [dbo].[DETALLE_INGRESO] ADD CONSTRAINT [DETALLE_APAFA_SERVICIO] FOREIGN KEY ([IDSER]) REFERENCES [dbo].[SERVICIO] ([IDSER])
GO
